config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
  root to: 'books#index'
  resources :books do
    resources :comments , only: %i[create ], module: :books
  end
  resources :reports do
    resources :comments , only: %i[create ], module: :reports
  end
  resources :users, only: %i[index show] do
    resource :relationships, only: %i[create destroy]
    scope module: :users do
      resources :followings, only: [:index]
      resources :followers, only: [:index]
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy, inverse_of: :follower
  has_many :followings, through: :active_relationships, source: :following

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :following_id, dependent: :destroy, inverse_of: :following
  has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :avatar

  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :uid, uniqueness: { scope: :provider }, if: -> { uid.present? }

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def following?(user)
    active_relationships.where(following_id: user.id).exists?
  end

  def followed_by?(user)
    passive_relationships.where(follower_id: user.id).exists?
  end

  def follow(user)
    active_relationships.find_or_create_by!(following_id: user.id)
  end

  def unfollow(user)
    relationship = active_relationships.find_by(following_id: user.id)
    relationship&.destroy!
  end
end

app/controllers/users/followers_controller.rb
# frozen_string_literal: true

class Users::FollowersController < ApplicationController
  def index
    @user  = User.find(params[:user_id])
    @users = @user.followers.order(id: :desc).page(params[:page])
  end
end

app/controllers/users/followings_controller.rb
# frozen_string_literal: true

class Users::FollowingsController < ApplicationController
  def index
    @user  = User.find(params[:user_id])
    @users = @user.followings.order(id: :desc).page(params[:page])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'GitHub') if is_navigational_format?
    else
      alert = t('devise.omniauth_callbacks.failure', kind: 'GitHub', reason: @user.errors.full_messages.join(', '))
      redirect_to new_user_session_url, alert: alert
    end
  end

  def failure
    redirect_to new_user_session_url
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protected

  # Override
  def update_resource(resource, params)
    if params[:password].blank?
      # パスワード変更を伴わない場合はオーバーライドする
      # current_passwordが残っていると、これを更新しようとしてエラーになるのでparamsから削除
      params.delete(:current_password)
      resource.update_without_password(params)
    else
      # パスワード変更を伴う場合はデフォルトの実装を使う
      super
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.order(:id).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end
end

app/views/users/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow' %>
    <% end %>
  <% end %>
<% end %>

<%= link_to  "following#{ user.followings.count}", user_followings_path(user) %><br>
<%= link_to  "followers#{user.followers.count}", user_followers_path(user) %><br>

app/views/users/_follow_form.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit t('views.follow.submit_unfollow') %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit t('views.follow.submit_follow') %>
    <% end %>
  <% end %>
<% end %>

<%= link_to  "#{t('views.follow.follow')}#{user.followings.count}", user_followings_path(user) %><br>
<%= link_to  "#{t('views.follow.follower')}#{user.followers.count}", user_followers_path(user) %><br>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with model: @user do |form| %>
  <p>ユーザーネーム<%= form.text_field :user_name %></p>
<p>自己紹介 : <%= form.text_field :introduce_yourself  %></p>
 <p>郵便番号 : <%= form.text_field :postal_code %></p>
 <p>住所 : <%= form.text_field :address %></p>
  <div><%= form.submit "保存" %></div>
<% end %>

app/views/users/index.html.erb
<h1><%= User.model_name.human %></h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th><%= User.human_attribute_name(:email) %></th>
      <th><%= User.human_attribute_name(:name) %></th>
      <th><%= User.human_attribute_name(:postal_code) %></th>
      <th><%= User.human_attribute_name(:address) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th>
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar.variant(resize_to_fill: [30, 30])%>
          <% end %>
        </th>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.postal_code %></td>
        <td><%= user.address %></td>
        <td><%= link_to t('views.common.show'), user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/users/show.html.erb
<h1><%= t('views.common.title_show', name: User.model_name.human) %></h1>

<p>
  <strong><%= User.human_attribute_name(:email) %>:</strong>
  <%= @user.email %>
</p>

<p>
  <strong><%= User.human_attribute_name(:name) %>:</strong>
  <%= @user.name %>
</p>

<p>
  <strong><%= User.human_attribute_name(:postal_code) %>:</strong>
  <%= @user.postal_code %>
</p>

<p>
  <strong><%= User.human_attribute_name(:address) %>:</strong>
  <%= @user.address %>
</p>

<p>
  <strong><%= User.human_attribute_name(:self_introduction) %>:</strong>
  <%= @user.self_introduction %>
</p>

<p>
  <strong><%= User.human_attribute_name(:avatar) %>:</strong>
  <% if @user.avatar.attached? %>
    <br>
    <%= image_tag @user.avatar.variant(resize_to_fill: [150, 150])%>
  <% end %>
</p>

<%= render 'follow_form', user: @user %>

<% if current_user == @user %>
  <%= link_to t('views.common.edit'), edit_user_registration_path %> |
<% end %>
<%= link_to t('views.common.back'), users_path %>