config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
  root to: 'books#index'
  resources :books do
    resources :comments , only: %i[create ], module: :books
  end
  resources :reports do
    resources :comments , only: %i[create ], module: :reports
  end
  resources :users, only: %i[index show] do
    resource :relationships, only: %i[create destroy]
    scope module: :users do
      resources :followings, only: [:index]
      resources :followers, only: [:index]
    end
  end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  def user_equal?(current_user)
    user == current_user
  end
end

app/controllers/reports/comments_controller.rb
# frozen_string_literal: true

class Reports::CommentsController < CommentsController
  
  private

  def set_commentable
    @commentable = Report.find(params[:report_id])
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]
  before_action :contribute_user?, only: %i[edit update destroy]
  before_action :set_commentable, only: %i[create]

  # GET /reports
  def index
    @reports = Report.all.order(:id).page(params[:page])
  end

  # GET /reports/1
  def show
    @comment = Comment.new
    @comments = @report.comments.includes(:user).order(:id).page(params[:page])
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit; end

  # POST /reports
  def create
    @report = Report.new(report_params)
    if @report.save
      redirect_to @report, notice: t('controllers.common.notice_create', name: Report.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(report_params)
      redirect_to @report, notice: t('controllers.common.notice_update', name: Report.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_url, notice: t('controllers.common.notice_destroy', name: Report.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def report_params
    params.require(:report).permit(:title, :description).merge(user_id: current_user.id)
  end

  def contribute_user?
    return true if current_user == @report.user

    redirect_to reports_path
    flash[:alert] = t('controllers.report.notice_alert')
  end
end

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
<% if report.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

  <ul>
    <% report.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t('views.common.title_edit', name: Report.model_name.human) %></h1>

<%= render 'form', report: @report %>

<%= link_to  t('views.common.show'), @report %> |
<%= link_to  t('views.common.back'), reports_path %>

app/views/reports/index.html.erb
<h1><%= Report.model_name.human%></h1>

<table>
  <thead>
    <tr>
      <th><%= Report.human_attribute_name(:title) %></th>
      <th><%= Report.human_attribute_name(:description) %></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
    <tr>
      <td><%= report.title %></td>
      <td><%= report.description %></td>
      <td><%= link_to t('views.common.show'), report %></td>
      <% if report.user_equal?(current_user) %>
        <td><%= link_to t('views.common.edit'), edit_report_path(report) %></td>
        <td><%= link_to t('views.common.destroy'), report, method: :delete, data: { confirm: t('views.common.delete_confirm') } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @reports %>

<%= link_to t('views.common.new'), new_report_path %>

app/views/reports/new.html.erb
<h1><%= t('views.common.title_new', name: Report.model_name.human) %></h1>

<%= render 'form', report: @report %>

<%= link_to t('views.common.back'), reports_path %>

app/views/reports/show.html.erb
<h1><%= t('views.common.title_show', name: Report.model_name.human) %></h1>

<p>
  <strong><%= Report.human_attribute_name(:title) %></strong>
  <%= @report.title %>
</p>

<p>
  <strong><%= Report.human_attribute_name(:description) %></strong>
  <%= @report.description %>
</p>

<% if current_user?(@report) %>
  <%= link_to  t('views.common.edit'), edit_report_path(@report) %> |
<% end %>
<%= link_to  t('views.common.back'), reports_path %><br>

<%= render 'comments/comment', commentable: @report, comment: @comment,comments: @comments  %> 