config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
  root to: 'books#index'
  resources :books do
    resources :comments , only: %i[create ], module: :books
  end
  resources :reports do
    resources :comments , only: %i[create ], module: :reports
  end
  resources :users, only: %i[index show] do
    resource :relationships, only: %i[create destroy]
    scope module: :users do
      resources :followings, only: [:index]
      resources :followers, only: [:index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="menu-container">
        <div class="title"><%= t('.menu') %></div>
        <ul>
          <li>
            <%= link_to Book.model_name.human, books_path %>
          </li>
          <li>
            <%= link_to User.model_name.human, users_path %>
          </li>
           <li>
            <%= link_to Report.model_name.human, reports_path %>
          </li>
        </ul>
        <div class="title"><%= t('.sign_in_as', email: current_user.email) %></div>
        <ul>
          <li>
            <%= link_to t('devise.registrations.edit.title'), edit_user_registration_path %>
          </li>
          <li>
            <%= link_to t('views.common.sign_out'), destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <% if notice.present? %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p id="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>